services:

  kafka:
    image: confluentinc/cp-kafka:7.8.2
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
      - "29092:29092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: KAFKA_UI://kafka:29092,JAVA_SERVICE://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,BROKER://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: KAFKA_UI:PLAINTEXT,JAVA_SERVICE:PLAINTEXT,CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: KAFKA_UI://kafka:29092,JAVA_SERVICE://localhost:9092,BROKER://kafka:9094
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.2.0
    container_name: kafka-ui
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: products_cluster
      # Address where to connect
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml