spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: off

# custom kafka properties
kafka:
  servers:
    products:
      bootstrap-server: localhost:9092
      steps:
        products:
          topic-name: products
          group-id: products
        category-assignment:
          topic-name: category-assignment
          group-id: category-assignment-group
        price-assignment:
          topic-name: price-assignment
          group-id: price-assignment-group

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"