spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: off

# custom kafka properties
kafka:
  servers:
    products:
      bootstrap-server: localhost:9092
      group-id: products
      steps:
        stock-assignment:
          topic-name: stock-assignment
        category-assignment:
          topic-name: category-assignment
        price-assignment:
          topic-name: price-assignment

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"