spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: off

# custom kafka properties
kafka:
  servers:
    products:
      bootstrap-server: localhost:9092
      consumers:
        products:
          topic-name: products
          group-id: products
        products-ce-structured:
          topic-name: products-ce-structured
          group-id: products-ce-structured
        products-ce-binary:
          topic-name: products-ce-binary
          group-id: products-ce-binary

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"