spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: off
  datasource:
    name: products
    driver-class-name: org.postgresql.Driver
    hikari.maxLifetime: 600000
    url: jdbc:postgresql://localhost:5432/products
    username: username1
    password: password1
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

# custom kafka properties
kafka:
  servers:
    products:
      bootstrap-server: localhost:9092
      group-id: products
      steps:
        stock-assignment:
          topic-name: stock-assignment
        category-assignment:
          topic-name: category-assignment
        price-assignment:
          topic-name: price-assignment

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"