spring:
  kafka:
    consumer:
      group-id: products-consumers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

products-consumers:
  topic-name: products
  group-id: 1234

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"