name: backend-build-and-test
description: 'backend-build-and-test'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: gradle

    - shell: bash
      run: |
        chmod +x gradlew 
        ./gradlew clean check
