name: backend-build-and-test
description: 'backend-build-and-test'
inputs:
  code-cov:
    description: code-cov
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: gradle

    - shell: bash
      run: |
        chmod +x gradlew
        ./gradlew clean check

    - name: Upload test report on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: build/reports/tests/test

    - name: Upload Gradle problems report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-problems-report
        path: build/reports/problems

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/
        retention-days: 1

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ inputs.code-cov }}