name: build-and-test
on:
  push:
    branches:
      - '**'        # matches every branch
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew clean check