name: nightly-build

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/backend-build-and-test
        with:
          code-cov: ${{ secrets.CODECOV_TOKEN }}
